---
extends: default

rules:
  document-start:
    # workflows don't have ---
    ignore: |
      /.github/workflows/
  line-length:
    max: 132
    allow-non-breakable-words: true
    allow-non-breakable-inline-mappings: true
    ignore: |
      /.github/workflows/lint.yaml
  truthy:
    # "on" as a key in workflows confuses things
    ignore: |
      /.github/workflows/
